add_newline = false

format = """
[╭─](bold blue) $username$hostname $directory$git_branch$git_status
[╰─](bold blue) $cmd_duration$character"""

# Config user/machine 
[username]
show_always = true
format = "[$user]($style)"
style_user = "green"

[hostname]
ssh_only = false
format = "[@$hostname]($style)"
style = "green"

[cmd_duration]
min_time = 2_000
format = "[$duration](bold yellow) "

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold cyan"

[git_branch]
style = "bold purple"

[git_status]
style = "bold red"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
